#!/usr/bin/env python3
"""Stage 4: generate ~10% GENUINE no-call / irrelevance targets (config_sgod.IRRELEVANCE_CONFIG).

Kinds: out_of_scope (unrelated), chitchat, ambiguous (in-domain but under-specified),
procedure_question (how-to). All are labeled expected_tool=null, expected_permission="allowed"
so build_parity_trainset.py emits DEFLECT_VI (no <tool_call>). This is distinct from
permission_denial (an in-domain tool the role may not call -> REFUSAL_VI), handled by the domain plan.

No LLM labeling needed (the label is "no tool" by construction), but queries ARE generated by an
LLM for diversity, then anti-leaked against the eval set(s) + train.

Usage (LLM stage — runs on the reference infrastructure, needs OPENAI_API_KEY):
  OPENAI_API_KEY=... python3 datagen/generate_irrelevance.py --count 300 --output data/sgod/irrelevance.json
"""
import argparse
import json
import sys
import time
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import config_sgod as cfg  # noqa: E402
import simindex  # noqa: E402

SYS_DEFAULT = ("Bạn tạo dữ liệu kiểm thử NEGATIVE cho một chatbot quản lý tài sản tiếng Việt (nền tảng SGOD). "
               "Trả về MỘT mảng JSON các chuỗi câu tiếng Việt. KHÔNG giải thích.")


def kind_hint(kind, prompt_dir):
    return cfg.load_prompt(f"irrelevance_{kind}", cfg.IRRELEVANCE_CONFIG[f"{kind}_hint"], prompt_dir)


def gen_batch(client, system_text, kind, hint, n, model):
    up = f"Loại: {kind}. {hint}\nTạo {n} câu KHÁC NHAU. Trộn văn phong. Mảng JSON thuần."
    for attempt in range(5):
        try:
            r = client.chat.completions.create(
                model=model, temperature=1.15, max_tokens=1400, timeout=60,
                messages=[{"role": "system", "content": system_text}, {"role": "user", "content": up}])
            cfg.METER.add(r)
            t = (r.choices[0].message.content or "").strip()
            t = t[t.find("["): t.rfind("]") + 1] if "[" in t else "[]"
            return [s.strip() for s in json.loads(t) if isinstance(s, str) and len(s.strip()) >= 3]
        except json.JSONDecodeError:
            return []
        except Exception:  # noqa: BLE001
            cfg.METER.errors += 1
            time.sleep(3 * (attempt + 1))
    return []


def main():
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0],
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--count", type=int, default=300, help="total rows across all kinds")
    p.add_argument("--output", default=f"{cfg.DATA_DIR}/irrelevance.json")
    p.add_argument("--batch", type=int, default=15)
    p.add_argument("--model", default=cfg.GEN_MODEL)
    p.add_argument("--train", default=f"{cfg.DATA_DIR}/train.jsonl", help="anti-leak against (skipped if missing)")
    p.add_argument("--only-kind", default="", help="generate only this kind at --count (e.g. procedure_question)")
    p.add_argument("--prompt-dir", default=cfg.PROMPT_DIR,
                   help="optional irrelevance_system.md / irrelevance_<kind>.md overrides")
    args = p.parse_args()

    client = cfg.require_openai_client()
    system_text = cfg.load_prompt("irrelevance_system", SYS_DEFAULT, args.prompt_dir)

    accepted = simindex.build_leak_index(
        cfg.EVAL_SETS_FOR_LEAKAGE,
        train_paths=[args.train] if cfg.repo_path(args.train).exists() else [])
    print(f"Leakage index: {len(accepted)} reference queries (threshold {cfg.LEAKAGE_THRESHOLD})")

    frac = cfg.IRRELEVANCE_CONFIG["kinds"]
    if args.only_kind:
        if args.only_kind not in frac:
            raise SystemExit(f"unknown kind {args.only_kind!r}; known: {sorted(frac)}")
        frac = {args.only_kind: 1.0}
    out_path = cfg.repo_path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out = []
    role_cycle = list(cfg.CASE_ROLES)
    for kind, f in frac.items():
        target = max(1, int(round(args.count * f)))
        hint = kind_hint(kind, args.prompt_dir)
        got = tries = 0
        while got < target and tries < target // args.batch + 8:
            tries += 1
            for q in gen_batch(client, system_text, kind, hint, min(args.batch, max(4, target - got)), args.model):
                if got >= target:
                    break
                if accepted.check_and_add(q, cfg.LEAKAGE_THRESHOLD):
                    out.append({"id": f"IRR-{kind[:3]}-{got:04d}",
                                "category": "edge_case" if kind == "ambiguous" else "out_of_scope",
                                "user_role": role_cycle[got % len(role_cycle)], "input": q,
                                "expected_tool": None, "expected_params": {},
                                "expected_permission": "allowed", "_irrelevance_kind": kind})
                    got += 1
        print(f"  {kind}: {got}/{target}", flush=True)
        out_path.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")

    out_path.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    print("by kind:", dict(Counter(c["_irrelevance_kind"] for c in out)))
    print(f"SUMMARY irrelevance: rows={len(out)} target={args.count} -> {out_path} | {cfg.METER.summary()}")
    return 0 if out else 1


if __name__ == "__main__":
    raise SystemExit(main())
