#!/usr/bin/env python3
"""Generate tools/sgod/tool_api_mapping.md from sgod_tools.json + tool_policy.json + the spec.

The Markdown is fully derived — never edit it by hand. Output is deterministic (no timestamps), so
`--check` can verify that the committed file matches what the current JSON would produce (use in PR review/CI).

Columns: tool · service · method · endpoint · jwt_scoped · roles · writes · resolve · tham số.
A second section "Loại trừ (spec §4)" lists the blocklisted endpoints with the symptom quoted from the spec,
plus the chat owner-only rule.

Usage:
  python tools/sgod/gen_tool_api_mapping.py [--tools ...] [--policy ...] [--roles ...] [--spec ...]
                                            [--out tools/sgod/tool_api_mapping.md] [--check]
Exit 0 on success (or when --check finds the file up to date), 1 otherwise.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import validate_tools as vt  # noqa: E402  (same directory; spec parsing + path helpers)

HEADER = "<!-- GENERATED by tools/sgod/gen_tool_api_mapping.py — do not edit by hand -->"
YES, NO, NONE = "✓", "✗", "—"


def _md(s: str) -> str:
    """Escape pipes so a value cannot break the table."""
    return str(s).replace("|", "\\|")


def _param_cell(fn: dict) -> str:
    props = (fn.get("parameters") or {}).get("properties") or {}
    required = set((fn.get("parameters") or {}).get("required") or [])
    parts = []
    for name, schema in props.items():
        schema = schema if isinstance(schema, dict) else {}
        label = f"`{name}`" + ("\\*" if name in required else "")
        typ = schema.get("type", "?")
        extra = f" enum: {', '.join(map(str, schema['enum']))}" if schema.get("enum") else ""
        parts.append(f"{label} ({typ}{extra})")
    return "; ".join(parts) if parts else NONE


def render(tools: list, policy: dict, roles_doc: dict, spec_text: str) -> str:
    blocklist = vt.parse_spec_blocklist(spec_text)
    owner_role = (roles_doc.get("tiers") or {}).get("enterprises", "company_admin")
    n_read = sum(1 for t in tools if not t["x_sgod"].get("writes"))
    roles = list(roles_doc.get("roles") or [])
    per_role = ", ".join(f"{r}: {len(vt.tools_for_role(tools, policy, r))}" for r in roles)

    lines = [
        HEADER,
        "# Bảng ánh xạ tool → SGOD API (sgod_tools v1 — bản nháp)",
        "",
        "Nguồn: `tools/sgod/sgod_tools.json` · `tools/sgod/tool_policy.json` · `tools/sgod/roles.json` · "
        "`docs/sgod-api-reference.md`. Sinh lại bằng `python tools/sgod/gen_tool_api_mapping.py`; "
        "kiểm tra đồng bộ bằng `--check`.",
        "",
        f"Số tool: **{len(tools)}** · chỉ đọc (writes=false): **{n_read}/{len(tools)}** · số tool theo vai trò: {per_role}.",
        "",
        "Mọi tool đều gọi qua gateway với hai header (`x-api-key` của service + `Authorization: Bearer <JWT người dùng>`); "
        "`jwt_scoped` ✓ nghĩa là kết quả đã được SGOD giới hạn theo tenant/tài khoản của JWT, nên **không có** tham số "
        "company/tenant/enterprise id (spec §1). `Resolve` là bước tra tên → id mà executor chạy trước khi gọi endpoint "
        "(một lượt gọi tool duy nhất từ phía model). Tham số đánh dấu \\* là bắt buộc.",
        "",
        "| Tool | Service | Method | Endpoint | jwt_scoped | Roles | Writes | Resolve | Tham số |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for t in tools:
        fn, x = t["function"], t["x_sgod"]
        pol = policy.get(fn["name"], {})
        roles_cell = ", ".join(pol.get("roles") or x.get("allowed_roles") or [])
        resolve = f"`{x['resolve']}`" if x.get("resolve") else NONE
        lines.append(
            f"| `{fn['name']}` | {x['service']} | {x['method']} | `{x['path']}` | "
            f"{YES if x.get('jwt_scoped') else NO} | {roles_cell} | {YES if x.get('writes') else NO} | "
            f"{_md(resolve)} | {_md(_param_cell(fn))} |"
        )

    lines += [
        "",
        "## Loại trừ (spec §4)",
        "",
        "Các endpoint dưới đây **không được** đưa vào bất kỳ tool nào; `validate_tools.py` sẽ báo lỗi nếu vi phạm. "
        "Triệu chứng trích nguyên văn từ bảng \"Known issues\" của spec.",
        "",
        "| Method | Endpoint | Triệu chứng (trích spec §4) |",
        "|---|---|---|",
    ]
    for (method, path), symptom in sorted(blocklist.items()):
        lines.append(f"| {method} | `{path}` | {_md(symptom)} |")
    lines += [
        "",
        f"**Quy tắc chat-service:** mọi path `/sgod-chat/v1/...` chỉ được mở cho vai trò chủ doanh nghiệp "
        f"(`{owner_role}`). Spec §4: {_md(vt.chat_owner_symptom(spec_text))}",
        "",
        "Ngoài ra, v1 **không** có tool ghi (POST/PATCH/PUT/DELETE) — spec §3 \"Start read-only\"; mọi thao tác ghi "
        "sẽ được cân nhắc sau tag `tools-v1` và phải qua bước xác nhận.",
        "",
    ]
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--tools", default="tools/sgod/sgod_tools.json")
    ap.add_argument("--policy", default="tools/sgod/tool_policy.json")
    ap.add_argument("--roles", default="tools/sgod/roles.json")
    ap.add_argument("--spec", default="docs/sgod-api-reference.md")
    ap.add_argument("--out", default="tools/sgod/tool_api_mapping.md")
    ap.add_argument("--check", action="store_true",
                    help="do not write; exit 1 if --out differs from what would be generated")
    args = ap.parse_args(argv)

    errors: list[str] = []
    tools = vt.load_json(vt.resolve_path(args.tools), "tools", errors)
    policy = vt.load_json(vt.resolve_path(args.policy), "policy", errors)
    roles_doc = vt.load_json(vt.resolve_path(args.roles), "roles", errors)
    spec_path = vt.resolve_path(args.spec)
    spec_text = spec_path.read_text(encoding="utf-8") if spec_path.exists() else ""
    if not spec_text:
        errors.append(f"spec: file not found or empty: {spec_path}")
    for e in errors:
        print(f"ERROR {e}")
    if errors:
        print(f"gen_tool_api_mapping: FAIL — {len(errors)} error(s)")
        return 1

    text = render(tools, policy, roles_doc, spec_text)
    out = Path(args.out)
    if not out.is_absolute() and not out.parent.exists():
        out = vt.REPO / args.out
    if args.check:
        current = out.read_text(encoding="utf-8") if out.exists() else None
        if current != text:
            print(f"gen_tool_api_mapping: STALE — {out} differs from the generated output; re-run without --check")
            return 1
        print(f"gen_tool_api_mapping: OK — {out} is up to date ({len(tools)} tools)")
        return 0
    out.write_text(text, encoding="utf-8")
    print(f"gen_tool_api_mapping: OK — wrote {out} ({len(tools)} tools, {text.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
