#!/usr/bin/env python3
"""Deterministic SYNTHETIC predictions for CI / smoke tests of the eval stack (no model involved).

    python scripts/make_sample_pred.py --out data/public/sample_pred.jsonl [--seed 1]
        [--eval data/public/xlam_2k.eval.json] [--preamble prompts/system_preamble_v0.txt]
        [--wrong-tool-every 7] [--drop-arg-every 11] [--empty-every 23] [--date <iso>]

Walks the eval records in order (1-based position ``i``) and writes one prediction per record:

* ``i % empty_every == 0``      -> no tool call, a short Vietnamese "cannot help" text  (scores no_tool/wrong_tool)
* else ``i % wrong_tool_every`` -> another tool from the record's own list (or ``unknown_tool``)  (wrong_tool)
* else ``i % drop_arg_every``   -> the right tool with EMPTY arguments  (missing_params when params expected)
* otherwise                     -> the gold tool with exactly the gold arguments  (ok)

The header mirrors ``predict_toolcall.py``: ``model = "synthetic-sample"``, real ``sha256_eval`` of the
eval file, ``sha256_tools = null`` (per-record tools), ``sha256_preamble`` of the preamble file,
``git_sha = null`` (synthetic output has no code provenance, and a null keeps regeneration byte-for-byte
across commits). So ``eval_toolcall.py`` header check PASSES on the committed eval and the expected
strict accuracy is roughly ``1 - 1/empty - 1/wrong - 1/drop``. Seeds only affect which wrong tool is
picked; ``--date`` lets the committed sample be regenerated byte-for-byte (default: today, UTC).

CI dependency
-------------
``.github/workflows/ci.yml`` runs ``eval_toolcall.py`` on ``data/public/sample_pred.jsonl`` WITH the
header check, so the committed samples are valid only while ``data/public/xlam_2k.eval.json`` and
``prompts/system_preamble_v0.txt`` are byte-identical to the files they were generated from.
Whoever regenerates the public slice or edits preamble v0 MUST re-run the two commands below
(same ``--date``) and commit both files; ``cmp`` against the previous files shows what moved.

Committed samples (regeneration commands -- exact, deterministic):
    python scripts/make_sample_pred.py --seed 1 --date 2026-09-13 --out data/public/sample_pred.jsonl
    python scripts/make_sample_pred.py --seed 2 --wrong-tool-every 5 --drop-arg-every 9 --empty-every 19 \
        --date 2026-09-13 --out data/public/sample_pred_b.jsonl
"""
from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import random
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
FALLBACK_TEXT = "Xin lỗi, tôi không hỗ trợ được yêu cầu này."


def sha256_file(path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def sha256_text(text: str) -> str:
    """sha256 of text after .strip() -- the contract's convention for the preamble hash."""
    return hashlib.sha256(text.strip().encode("utf-8")).hexdigest()


def rel(path) -> str:
    """Path relative to the repo root when inside it (keeps committed headers machine-independent)."""
    try:
        return Path(path).resolve().relative_to(REPO).as_posix()
    except ValueError:
        return str(path)


def tool_names(rec: dict) -> list[str]:
    return [(t.get("function") or {}).get("name") or t.get("name") for t in rec.get("tools") or []]


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--out", required=True)
    p.add_argument("--eval", default=str(REPO / "data/public/xlam_2k.eval.json"))
    p.add_argument("--preamble", default=str(REPO / "prompts/system_preamble_v0.txt"))
    p.add_argument("--seed", type=int, default=1)
    p.add_argument("--wrong-tool-every", type=int, default=7)
    p.add_argument("--drop-arg-every", type=int, default=11)
    p.add_argument("--empty-every", type=int, default=23)
    p.add_argument("--date", default=None, help="ISO date for the header (default: today UTC)")
    args = p.parse_args(argv)

    for path, label in ((args.eval, "--eval"), (args.preamble, "--preamble")):
        if not Path(path).exists():
            print(f"error: {label} file not found: {path}", file=sys.stderr)
            return 1
    for v, label in ((args.wrong_tool_every, "--wrong-tool-every"), (args.drop_arg_every, "--drop-arg-every"),
                     (args.empty_every, "--empty-every")):
        if v < 1:
            print(f"error: {label} must be >= 1 (use a huge number to disable)", file=sys.stderr)
            return 1

    with open(args.eval, encoding="utf-8") as f:
        records = json.load(f)
    if isinstance(records, dict):
        records = records.get("records") or records.get("cases") or records.get("data")
    rng = random.Random(args.seed)

    header = {
        "header": True,
        "model": "synthetic-sample",
        "backend": "synthetic",
        "base_url_host": None,
        "date": args.date or _dt.datetime.now(_dt.timezone.utc).date().isoformat(),
        "git_sha": None,        # synthetic: no code provenance; null keeps regeneration byte-for-byte
        "sha256_eval": sha256_file(args.eval),
        "sha256_tools": None,
        "sha256_preamble": sha256_text(Path(args.preamble).read_text(encoding="utf-8")),
        "sampling": {"temperature": 0, "synthetic": True, "seed": args.seed,
                     "wrong_tool_every": args.wrong_tool_every, "drop_arg_every": args.drop_arg_every,
                     "empty_every": args.empty_every},
        "n": len(records),
        "eval_path": rel(args.eval),
        "preamble_path": rel(args.preamble),
    }

    counts = {"ok": 0, "empty": 0, "wrong_tool": 0, "drop_args": 0}
    lines = [json.dumps(header, ensure_ascii=False)]
    for i, rec in enumerate(records, 1):
        gold_tool = rec.get("expected_tool")
        gold_args = rec.get("expected_params") or {}
        if i % args.empty_every == 0 or gold_tool is None:
            calls, text, kind = [], FALLBACK_TEXT, "empty"
        elif i % args.wrong_tool_every == 0:
            others = [n for n in tool_names(rec) if n and n != gold_tool]
            name = rng.choice(sorted(others)) if others else "unknown_tool"
            calls, kind = [{"name": name, "arguments": dict(gold_args)}], "wrong_tool"
            text = "<tool_call>" + json.dumps(calls[0], ensure_ascii=False) + "</tool_call>"
        elif i % args.drop_arg_every == 0:
            calls, kind = [{"name": gold_tool, "arguments": {}}], "drop_args"
            text = "<tool_call>" + json.dumps(calls[0], ensure_ascii=False) + "</tool_call>"
        else:
            calls, kind = [{"name": gold_tool, "arguments": dict(gold_args)}], "ok"
            text = "<tool_call>" + json.dumps(calls[0], ensure_ascii=False) + "</tool_call>"
        counts[kind] += 1
        lines.append(json.dumps({
            "id": rec.get("id"),
            "user_role": rec.get("user_role"),
            "predicted_tool_calls": calls,
            "predicted_tool": calls[0]["name"] if calls else None,
            "raw_text": text,
            "finish_reason": "stop",
            "latency_ms": 10 + (i * 7919) % 90,      # deterministic pseudo-latency
            "error": None,
        }, ensure_ascii=False))

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    exp = 1 - 1 / args.empty_every - 1 / args.wrong_tool_every - 1 / args.drop_arg_every
    print(f"SUMMARY make_sample_pred: n={len(records)} seed={args.seed} ok={counts['ok']} "
          f"wrong_tool={counts['wrong_tool']} drop_args={counts['drop_args']} empty={counts['empty']} "
          f"expected_acc~{100 * exp:.1f}% (upper bound; drop_args only fails when params expected) "
          f"sha256_eval={header['sha256_eval'][:16]} -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
